#!/usr/bin/env bash
# One command: bring up a local Home Assistant with this branch's OpenDisplay
# integration, reachable at http://127.0.0.1:8123. Native Python via uv --
# no Docker (maintainer ruling 2026-08-30: maximum KISS, no container
# runtime dependency). See dev/README.md for the full workflow.
set -euo pipefail

DEV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEV_DIR/.." && pwd)"
HA_CONFIG="$DEV_DIR/ha-config"
PID_FILE="$HA_CONFIG/.harness.pid"
LOG_FILE="$HA_CONFIG/ha.log"
HA_PORT="${HA_PORT:-8123}"
# 127.0.0.1, not localhost (tier-1 review, finding 3): macOS resolves
# "localhost" to ::1 (IPv6) first, and HA's own auth/http stack can
# mismatch across that split (reproduced live -- a white designer page,
# /auth/token failures logged against ::1, while 127.0.0.1 worked
# immediately). Every probe, printed URL, and doc example derives from this
# one value, so fixing it here fixes all of them at once.
HA_URL="http://127.0.0.1:${HA_PORT}"
# Every wait/poll curl below uses this -- an HA that accepts the TCP
# connection but hangs mid-response (wedged onboarding storage, a stuck
# component setup) must not turn a bounded poll into an unbounded one
# (adversarial review round 3, finding 5).
CURL_TIMEOUT=(--connect-timeout 5 --max-time 10)

command -v uv >/dev/null 2>&1 || {
  echo "ERROR: uv not found on PATH (https://docs.astral.sh/uv/)." >&2
  exit 1
}

# pyproject.toml pins requires-python >=3.14.2, and __init__.py relies on
# syntax (an unparenthesized except-tuple) that is a SyntaxError below 3.14.
# uv resolves the interpreter itself, but confirm loudly rather than let a
# stale/pre-existing uv-managed interpreter fail with a confusing traceback
# three layers into hass's own startup.
resolved_version="$(cd "$REPO_ROOT" && uv run --no-default-groups --group dev python3 -c \
  'import sys; print(".".join(map(str, sys.version_info[:3])))')"
resolved_major="${resolved_version%%.*}"
resolved_minor="$(cut -d. -f2 <<<"$resolved_version")"
if ((resolved_major != 3 || resolved_minor < 14)); then
  echo "ERROR: uv resolved Python $resolved_version, but this repo requires >=3.14.2" \
    "(pyproject.toml). Run 'uv python install 3.14' and retry." >&2
  exit 1
fi

mkdir -p "$HA_CONFIG"

# configuration.yaml's `http:` key !includes this file so hass actually
# binds $HA_PORT -- without it, HA_PORT only relabels this script's own
# probe URLs while hass always binds its default 8123 regardless, so a
# real 8123 conflict on a non-default $HA_PORT run went undiagnosed (and,
# worse, a resulting death got misdiagnosed as the TCC crash below --
# reproduced live, round 3 of adversarial review). Regenerated on every
# start; gitignored like everything else under ha-config/ except
# configuration.yaml itself.
cat >"$HA_CONFIG/http_port.yaml" <<EOF
# GENERATED by dev/run.sh on every start -- do not edit by hand, it will be
# overwritten. Sets http.server_port to \$HA_PORT (see dev/run.sh) so this
# harness's own probes/preflight port-check and the port hass actually
# binds are always the same port.
server_port: $HA_PORT
EOF

# Home Assistant only looks for custom_components/ inside its own config
# directory (it adds that directory to sys.path specifically so
# `import custom_components` resolves) -- it never walks up from the repo
# checkout to find one. Symlink this branch's integration in, same effect
# as the old Docker bind-mount, kept in sync automatically since it's a
# symlink (no copy to go stale). Verified necessary: without this, HA 2026.8's
# own core-shipped `opendisplay` integration silently answers the domain
# instead (same name, no error) -- see dev/README.md.
mkdir -p "$HA_CONFIG/custom_components"
integration_link="$HA_CONFIG/custom_components/opendisplay"
if [[ -e "$integration_link" && ! -L "$integration_link" ]]; then
  echo "ERROR: $integration_link exists and is a real directory, not a" \
    "symlink -- refusing to ln -sfn over it (that either fails outright or" \
    "silently nests the link inside it, depending on the platform)." \
    "Remove it by hand first if it's stale: rm -rf $integration_link" >&2
  exit 1
fi
ln -sfn "$REPO_ROOT/custom_components/opendisplay" "$integration_link"

already_running=false
if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
  already_running=true
fi

if [[ "$already_running" == false ]]; then
  if [[ -f "$PID_FILE" ]]; then
    echo "run: stale PID file (process gone) -- removing." >&2
    rm -f "$PID_FILE"
  fi
  # Port-free check: only fail if something OTHER than our own (stopped)
  # instance holds it -- a bare TCP probe can't tell whose process that is,
  # so this is best-effort; hass binding the port below is the authoritative
  # check (it fails loudly and this script's wait-loop below times out).
  if (exec 3<>"/dev/tcp/127.0.0.1/$HA_PORT") 2>/dev/null; then
    exec 3>&- 3<&-
    echo "ERROR: port $HA_PORT is already in use by something else." \
      "Free it, or set HA_PORT=<other-port> and rerun." >&2
    exit 1
  fi

  echo "run: starting Home Assistant (uv run --group dev hass --config dev/ha-config)..."
  (
    cd "$REPO_ROOT"
    nohup uv run --no-default-groups --group dev hass --config "$HA_CONFIG" \
      >"$LOG_FILE" 2>&1 &
    echo $! >"$PID_FILE"
  )
else
  echo "run: already running (pid $(cat "$PID_FILE"))."
fi

# --- Shared helpers (used by the wait loop below AND the final liveness
# check after onboarding -- a process can die at either point, and both get
# the identical crash diagnosis rather than two different, inconsistent
# messages depending on exactly when it happened) ---

ha_is_actually_up() {
  [[ -f "$PID_FILE" ]] || return 1
  kill -0 "$(cat "$PID_FILE")" 2>/dev/null || return 1
  curl -sf "${CURL_TIMEOUT[@]}" -o /dev/null "$HA_URL/manifest.json" || return 1
  return 0
}

# Prints the last N lines of a file with a labeled header, or says why it
# couldn't -- the shared "show me what happened" tail every failure path
# below uses, so a failure never just says "check the log" without also
# showing some of it right here.
tail_with_header() {
  local file="$1" label="$2" lines="${3:-30}"
  echo "--- last $lines lines: $label ($file) ---" >&2
  if [[ -s "$file" ]]; then
    tail -n "$lines" "$file" >&2
  else
    echo "(empty or missing)" >&2
  fi
}

# Prints a diagnosis for "the hass process is not up" and exits 1. The
# crash signature is specific and narrow, on purpose (round 3 of
# adversarial review): a NON-EMPTY macOS Python fault dump containing
# either `__TCC_CRASHING_DUE_TO_PRIVACY_VIOLATION__` or `Fatal Python
# error` -- nothing else counts. Two earlier, broader signatures were both
# reproduced as false positives and removed:
#   - "a .fault file exists" alone -- Home Assistant creates an empty one
#     on ordinary healthy boots too, via Python's own faulthandler
#     pre-registration.
#   - grepping $LOG_FILE (the regular stdout/stderr log) for
#     "corebluetooth\|bluetooth\|tcc" -- routine, unrelated cascade
#     failures mention "bluetooth" in perfectly ordinary log lines (e.g.
#     "Setup failed for 'bluetooth': Could not setup dependencies", or the
#     "Could not find Bluetooth device with address ..." reachability
#     message _drawcustom_for_device's own diagnostics produce), so a
#     plain port-8123-bind failure (nothing to do with TCC at all) matched
#     this arm and printed the full TCC remediation. Reproduced live and
#     removed entirely -- the fault dump is the only place this decision
#     is made now.
report_process_death_and_exit() {
  local context="$1"
  echo
  echo "ERROR: $context" >&2

  local fault_file="$HA_CONFIG/home-assistant.log.fault"
  local is_tcc_crash_signature=false
  if [[ -s "$fault_file" ]] && \
     grep -qE '__TCC_CRASHING_DUE_TO_PRIVACY_VIOLATION__|Fatal Python error' "$fault_file" 2>/dev/null; then
    is_tcc_crash_signature=true
  fi

  if [[ "$is_tcc_crash_signature" == true ]]; then
    cat <<'EOF' >&2

This matches the macOS/TCC CoreBluetooth crash (dev/README.md's "macOS /
CoreBluetooth caveat"): opendisplay's bluetooth_adapters manifest
dependency touches real CoreBluetooth, and macOS's TCC privacy framework
can hard-abort a process without an app-bundle Bluetooth entitlement --
this is a SIGABRT, not a Python exception, and nothing in this repo can
catch it. Timing is nondeterministic; it does not reliably happen on any
particular attempt.

Remediation to try: System Settings -> Privacy & Security -> Bluetooth ->
grant access to the terminal application running `uv` (Terminal.app,
iTerm2, etc.), then retry dev/run.sh. UNVERIFIED whether this actually
prevents the abort: TCC's permission model expects a signed .app bundle
declaring NSBluetoothAlwaysUsageDescription, which a uv-managed venv does
not have, so macOS may have nothing grantable to offer for a bare python3
process in the first place. Success without granting it is also possible
(this is nondeterministic, not "always fails") -- just not reliable.
EOF
  else
    echo "No macOS crash-dump evidence of the TCC/CoreBluetooth abort" \
      "dev/README.md documents (a plain kill, a port conflict, an" \
      "unrelated crash, or something else). See the log below for what" \
      "actually happened." >&2
  fi

  tail_with_header "$LOG_FILE" "hass stdout/stderr"
  tail_with_header "$fault_file" "macOS Python fault dump"
  exit 1
}



echo "run: waiting for HA to answer at $HA_URL ..."
deadline=$((SECONDS + 120))
until curl -sf "${CURL_TIMEOUT[@]}" -o /dev/null "$HA_URL/manifest.json"; do
  if ((SECONDS > deadline)); then
    echo "ERROR: HA did not become reachable at $HA_URL within 120s." \
      "Check the log: $LOG_FILE" >&2
    exit 1
  fi
  if [[ -f "$PID_FILE" ]] && ! kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    report_process_death_and_exit \
      "the hass process exited before becoming reachable."
  fi
  sleep 2
done
echo "run: HA is up."

echo "run: attempting scripted onboarding (idempotent, non-fatal if it fails)..."
if HA_URL="$HA_URL" HA_CONFIG="$HA_CONFIG" "$DEV_DIR/internal/onboarding.sh"; then
  onboarded=true
else
  onboarded=false
  echo
  echo "WARNING: scripted onboarding failed (see error above)." \
    "HA is still up — onboard by hand in the browser (dev/README.md, ~30s)." >&2
  echo
fi

# Final liveness check (adversarial review, B3): onboarding.sh's own HTTP
# calls can succeed moments before a TCC/CoreBluetooth abort takes the
# process down -- measured not to be bounded by the wait loop above. A
# curl that happened to land in that window must never produce a false
# "HA is up" banner; check both the tracked PID and a fresh reachability
# probe again, right here, not just inside the wait loop.
if ! ha_is_actually_up; then
  report_process_death_and_exit \
    "HA is not actually up (the process died, or stopped answering, sometime after the checks above passed)."
fi

cat <<EOF

============================================================
 OpenDisplay dev HA:  $HA_URL
============================================================
EOF
if [[ "$onboarded" == true ]]; then
  cat <<EOF
Login: username '${HA_DEV_USERNAME:-dev}', password '${HA_DEV_PASSWORD:-opendisplay-dev-harness}'
  (override next time with HA_DEV_USERNAME / HA_DEV_PASSWORD env vars)
EOF
else
  echo "Onboarding wizard should be waiting for you in the browser."
fi
cat <<EOF

Next steps — no OpenDisplay hardware needed:
  1. Open $HA_URL and log in.
  2. Stop it (fabricated entries are written straight into HA's storage,
     which must not be rewritten under a live process):
       dev/stop.sh
  3. uv run --group dev python dev/inject-displays.py — writes N fabricated
     OpenDisplay config entries (small mono / medium BWR / large BWRY, by
     default) into dev/ha-config/.storage/core.config_entries.
  4. dev/run.sh                 — bring HA back up; each fabricated entry
     sets up from its own cache with no BLE connection (sleepy-device
     fallback in __init__.py) and gets its device + entities created.

With real OpenDisplay hardware instead:
  1. Add the OpenDisplay integration via the UI and pair the device (needs
     a machine with real BLE reach — see dev/README.md's macOS caveat).
  2. dev/snapshot.sh   — capture that device's config/device/entity registry
     entries into dev/seed/ so you don't need hardware again.
  3. dev/restore.sh    — inject a dev/seed/ snapshot into a fresh instance.

Stop it:  dev/stop.sh
Logs:     tail -f $LOG_FILE
HA_PORT:  override the port (default 8123) by setting HA_PORT before run.sh

NOTE (macOS): opendisplay's bluetooth_adapters manifest dependency touches
real CoreBluetooth on native macOS, and this process has no app-bundle
Bluetooth entitlement to grant — macOS's TCC framework aborts it the first
time it tries, sometime between a few seconds and roughly a minute in (this
run made it past that window, going by the liveness check just above, but
a later stretch of idle time is not guaranteed to). See dev/README.md's
"macOS / CoreBluetooth caveat" for the measured details.
EOF
